// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgxdU-5HEM-DfJ3ON6yclgsLPJI22cXz4',
    appId: '1:537682313523:web:8396d90546411c0e8ebe46',
    messagingSenderId: '537682313523',
    projectId: 'take-order-app-2024',
    authDomain: 'take-order-app-2024.firebaseapp.com',
    storageBucket: 'take-order-app-2024.appspot.com',
    measurementId: 'G-XVB0RVSGV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0tFDyzZNDbHaj1wGPN-FEWkYUw9ARqzY',
    appId: '1:537682313523:android:ccadd3301bf97ea18ebe46',
    messagingSenderId: '537682313523',
    projectId: 'take-order-app-2024',
    storageBucket: 'take-order-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoR7s4tDOS69MvSRFjvMI44paIIOv0bU',
    appId: '1:537682313523:ios:db01f2eafc88a2328ebe46',
    messagingSenderId: '537682313523',
    projectId: 'take-order-app-2024',
    storageBucket: 'take-order-app-2024.appspot.com',
    iosBundleId: 'com.example.takeOrderApp',
  );
}
